server:
  port: 8081

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://192.168.10.205:8309/yeb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai"
    username: root
    password: jimy3k0519

  redis:
    timeout: 10000ms
    host: 192.168.10.205
    port: 8379
    database: 0 # 选择哪个库，默认0库
    lettuce:
      pool:
        max-active: 1024 # 最大连接数，默认 8
        max-wait: 10000ms # 最大连接阻塞等待时间，单位毫秒，默认 -1
        max-idle: 200 # 最大空闲连接，默认 8
        min-idle: 5

  # rabbitmq配置
  rabbitmq:
    # 用户名
    username: jimy3k
    # 密码
    password: jimy3k0519
    # 服务器地址
    host: 192.168.10.205
    # 端口
    port: 5672
    # 消息失败回调
    publisher-returns: true
    # 消息确认回调
    publisher-confirm-type: correlated

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 设置自动驼峰命名
    map-underscore-to-camel-case: false
    # 设置Mybatis-plus 全局配置
  global-config:
    db-config:
      table-prefix: t_        #设置实体类对应表名的统一前缀：t_
  # 配置类型别名所对应的包  mapper中 *Mapper.xml 使用类型别名，会用到。
  type-aliases-package: com.nicole.server.pojo
  # 配置Mapper映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml

jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT 加解密使用的密钥
  secret: yeb-secret
  # JWT的超期限时间（60*60*24）
  expiration: 604800
  # JWT 负载中拿到开头
  tokenHead: Bearer